-- Times da Copa do Mundo
INSERT INTO tbl_times (name, fase) VALUES ('México', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('África do Sul', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Coreia do Sul', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('República Tcheca', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Canadá', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Bósnia e Herzegovina', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Catar', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Suíça', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Brasil', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Marrocos', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Haiti', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Escócia', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Estados Unidos', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Paraguai', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Austrália', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Turquia', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Alemanha', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Curaçao', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Costa do Marfim', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Equador', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Holanda', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Japão', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Suécia', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Tunísia', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Bélgica', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Egito', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Irã', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Nova Zelândia', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Espanha', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Cabo Verde', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Arábia Saudita', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Uruguai', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('França', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Senegal', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Iraque', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Noruega', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Argentina', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Argélia', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Áustria', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Jordânia', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Portugal', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('República Democrática do Congo', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Uzbequistão', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Colômbia', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Inglaterra', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Croácia', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Gana', 'Fase de Grupos');
INSERT INTO tbl_times (name, fase) VALUES ('Panamá', 'Fase de Grupos');


--70 Torcedores para distribuir a quantidade de torcedores por time
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('enzo.silva45@email.com', 'senha123', 16);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('laura.martinez23@email.com', 'senha123', 44);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('marie.garcia85@email.com', 'senha123', 28);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('mateo.silva21@email.com', 'senha123', 14);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('laura.lee87@email.com', 'senha123', 2);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('leila.miller93@email.com', 'senha123', 45);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('marie.tanaka38@email.com', 'senha123', 29);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('david.rodriguez10@email.com', 'senha123', 11);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('hugo.muller45@email.com', 'senha123', 10);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('ana.muller23@email.com', 'senha123', 6);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('haruto.lopez55@email.com', 'senha123', 23);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('alex.rodriguez15@email.com', 'senha123', 47);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('noah.almeda25@email.com', 'senha123', 25);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('carlos.almeda47@email.com', 'senha123', 41);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('sam.dupont83@email.com', 'senha123', 13);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('smith.santos94@email.com', 'senha123', 15);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('olivia.garcia39@email.com', 'senha123', 7);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('haruto.rodriguez68@email.com', 'senha123', 41);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('ren.jones57@email.com', 'senha123', 23);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('ana.rodriguez99@email.com', 'senha123', 44);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('smith.smith91@email.com', 'senha123', 11);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('marie.davis30@email.com', 'senha123', 30);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('haruto.rodriguez91@email.com', 'senha123', 45);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('leila.davis97@email.com', 'senha123', 21);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('john.davis14@email.com', 'senha123', 21);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('sven.rodriguez18@email.com', 'senha123', 14);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('sarah.muller37@email.com', 'senha123', 42);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('mohamed.rossi92@email.com', 'senha123', 30);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('diego.rodriguez27@email.com', 'senha123', 16);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('leila.almeda43@email.com', 'senha123', 48);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('david.tanaka84@email.com', 'senha123', 26);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('ren.davis27@email.com', 'senha123', 33);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('mohamed.garcia16@email.com', 'senha123', 8);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('diego.jones97@email.com', 'senha123', 28);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('alex.garcia59@email.com', 'senha123', 25);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('alex.sato77@email.com', 'senha123', 17);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('leila.silva97@email.com', 'senha123', 47);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('enzo.almeda44@email.com', 'senha123', 42);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('ali.lopez47@email.com', 'senha123', 28);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('maria.sato10@email.com', 'senha123', 47);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('elena.lee32@email.com', 'senha123', 33);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('pedro.gonzalez91@email.com', 'senha123', 33);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('alex.miller29@email.com', 'senha123', 24);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('maria.almeda77@email.com', 'senha123', 1);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('alex.muller72@email.com', 'senha123', 2);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('enzo.dupont49@email.com', 'senha123', 16);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('john.davis82@email.com', 'senha123', 6);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('carlos.kim18@email.com', 'senha123', 35);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('arthur.martinez94@email.com', 'senha123', 31);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('leila.jones43@email.com', 'senha123', 34);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('alex.tanaka37@email.com', 'senha123', 35);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('sofia.gonzalez61@email.com', 'senha123', 43);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('ren.sato76@email.com', 'senha123', 29);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('enzo.davis38@email.com', 'senha123', 5);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('ali.silva85@email.com', 'senha123', 36);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('laura.hassan38@email.com', 'senha123', 1);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('smith.santos39@email.com', 'senha123', 5);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('mateo.muller19@email.com', 'senha123', 33);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('clara.rodriguez95@email.com', 'senha123', 32);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('ana.almeda26@email.com', 'senha123', 47);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('sarah.hassan70@email.com', 'senha123', 16);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('bjorn.tanaka34@email.com', 'senha123', 7);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('pedro.tanaka55@email.com', 'senha123', 28);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('hans.sato16@email.com', 'senha123', 44);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('pedro.santos61@email.com', 'senha123', 47);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('ali.lopez41@email.com', 'senha123', 13);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('sofia.almeda67@email.com', 'senha123', 9);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('hugo.jones45@email.com', 'senha123', 30);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('clara.garcia66@email.com', 'senha123', 36);
INSERT INTO tbl_torcedores (email, senha, time_id) VALUES ('pedro.santos93@email.com', 'senha123', 35);